#!/usr/bin/env bash
# ----------------------------------------------------------------------------------------------------------------------
# ls-git - https://github.com/eth-p/ls-git/ | MIT License | Copyright (C) 2018 Ethan P. (eth-p)
# ----------------------------------------------------------------------------------------------------------------------
# Copyright (c) 2018 Ethan P. (eth-p)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ----------------------------------------------------------------------------------------------------------------------
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[ -z "$PREFIX" ]        && PREFIX="$HOME"
[ "$PREFIX" = "$HOME" ] && INSTALL="$PREFIX/.bin" || INSTALL="$PREFIX/bin"
[ -d "$INSTALL" ]       || mkdir -p "$INSTALL"
INSTALL_FILE="$INSTALL/ls-git"

# ----------------------------------------------------------------------------------------------------------------------
# Dependency check:

depcheck() {
	printf "Checking for dependency %-15s " "'$1'..."
	if ! command -v "$1" &>/dev/null; then
		echo "Missing"
		exit 1
	fi

	echo "OK"
}

depcheck 'perl'
depcheck 'git'
depcheck 'tput'

# ----------------------------------------------------------------------------------------------------------------------
# Install:
echo "Installing to: $INSTALL"
if [ -n "$MINIFY" ] && command -v perltidy &>/dev/null; then
	# Install minified.
	perltidy --mangle --delete-all-comments "$HERE/ls-git.pl" -o "$INSTALL_FILE"
else
	# Install original.
	cp "$HERE/ls-git.pl" "$INSTALL_FILE"
fi

chmod 755 "$INSTALL_FILE"
